Add RecursionSafeAsyncCaller: safe to use for recursive calls
udoprog/tiny-async-java pull request #3
Opened 2016-11-07 08:57 UTC by gabrielgerhardsson

RecursionSafeAsyncCaller will try to run the call in the current thread as much as possible, while keeping track of recursion to avoid StackOverflowException in the thread. If recursion becomes too deep, the next call is deferred to a separate thread (normal thread pool). State is kept per-thread - stack overflow will be avoided for any thread that passes this code. It is vital to choose a suitable maximum recursion depth.

I should have split out the comment commit to a separate pull request I guess. Will do that next time.

2016-11-07 09:16 UTC, udoprog commented on tiny-async-core/src/main/java/eu/toolchain/async/RecursionSafeAsyncCaller.java
> +            // avoid stack overflow.
optional: prefer block comments for multiline comments.

2016-11-07 10:40 UTC, udoprog requested changes

2016-11-07 10:40 UTC, udoprog commented on tiny-async-core/src/main/java/eu/toolchain/async/RecursionSafeAsyncCaller.java
> +        Integer recursionDepth = recursionDepthPerThread.get();
make `final`. You can avoid incrementing the local variable with:
```java
final Integer recursionDepth = recursionDepthPerThread.get();
recursionDepthPerThread.set(recursionDepth + 1);

/*  */

recursionDepthPerThread.set(recursionDepth);
```

2016-11-07 10:40 UTC, udoprog commented on tiny-async-core/src/test/java/eu/toolchain/async/RecursionSafeAsyncCallerTest.java
> +    @SuppressWarnings("unchecked")
You can avoid this with:
```
@RunWith(MockitoJUnitRunner.class)
public class RecursionSafeAsyncCallerTest {
    @Mock
    public FutureDone<Object> done;
    /*  */
}
```

2016-11-07 10:40 UTC, udoprog commented on tiny-async-core/src/main/java/eu/toolchain/async/RecursionSafeAsyncCaller.java
> +        execute(new Runnable() {
Target version is `1.8`, prefer lambdas:
```java
execute(() -> caller.resolve(handle, result));
```

2016-11-07 14:02 UTC, gabrielgerhardsson commented on tiny-async-core/src/main/java/eu/toolchain/async/RecursionSafeAsyncCaller.java
> +        execute(new Runnable() {
Thanks, I've fixed

2016-11-07 14:02 UTC, gabrielgerhardsson commented on tiny-async-core/src/main/java/eu/toolchain/async/RecursionSafeAsyncCaller.java
> +        Integer recursionDepth = recursionDepthPerThread.get();
Have fixed

2016-11-07 14:02 UTC, gabrielgerhardsson commented on tiny-async-core/src/test/java/eu/toolchain/async/RecursionSafeAsyncCallerTest.java
> +    @SuppressWarnings("unchecked")
Have fixed

2016-11-07 21:33 UTC, udoprog approved these changes

2016-11-07 21:38 UTC, udoprog commented
Need a way to activate the stack guard, my suggestion would be to add a an option to `TinyAsyncBuilder`
and make use of it somewhere around here:
https://github.com/udoprog/tiny-async-java/blob/master/tiny-async-core/src/main/java/eu/toolchain/async/TinyAsyncBuilder.java#L111

Also remember to squash your commits.

After that, this looks good to me.

2016-11-08 08:49 UTC, gabrielgerhardsson commented
Thank you @udoprog. A couple of thoughts below.

Activation: After considering this a bit, I'm proposing that both the current caller and threadedCaller each gets an *optional* recursion guard instance in front of them. In my opinion it's valuable for both. The normal operation of both callers will remain in the default case, until heavy recursion is detected at which time the stack will be protected by deferring a recursive call. What do you think?

Squashing commits: I've done this now. Looks good?

2016-11-08 09:40 UTC, gabrielgerhardsson commented
Commited a suggestion for how to activate the stack guard.

2016-11-09 11:53 UTC, merged